language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
install:
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install pytest-cov
script:
  - black --check .
  - flake8 .
  - pytest --cov-report term --cov=ygoscanner
  - python main.py --help
after_success:
  - codecov
