language: python
dist: xenial
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 xvfb herbstluftwm
install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install pytest-cov
before_script:
  - "herbstluftwm &"
  - sleep 1
script:
  - black --check .
  - flake8 .
  - pytest --cov-report term --cov=src
  - python main.py --help
after_success:
  - codecov
